# -*- coding: utf-8 -*-
"""DSAI_HW4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EmTaKnyWQK3hR4_BCBJpNAbQl6Kne1rX
"""

!nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

"""

1.   prepare X, and Y
2.   seperate it into train and test set
3.   setup xgboost parameters
4.   fit data
5.   predict

"""

import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, Flatten, Conv2D, MaxPool2D, BatchNormalization, Activation
from keras.optimizers import Adam, SGD
from sklearn.preprocessing import MinMaxScaler
from statistics import mean
from keras import backend as K
from sklearn.metrics import f1_score, recall_score, precision_score, accuracy_score
from keras.callbacks import Callback
from sklearn.model_selection import train_test_split
from tqdm import tqdm 
from keras.utils import np_utils
import xgboost as xgb
import gc
np.set_printoptions(threshold=sys.maxsize)

main_path = 'drive/MyDrive/Colab Notebooks/dsai_hw4/dataset'

orders_DF = pd.read_csv(os.path.join(main_path, 'orders.csv'))  
prior_order_DF = pd.read_csv(os.path.join(main_path, 'order_products__prior.csv')) 
train_order_DF = pd.read_csv(os.path.join(main_path, 'order_products__train.csv')) 
products_DF = pd.read_csv(os.path.join(main_path, 'products.csv'))

orders_prior = orders_DF.loc[np.where(orders_DF['eval_set'] == 'prior')]
orders_train = orders_DF.loc[np.where(orders_DF['eval_set'] == 'train')]
orders_test  = orders_DF.loc[np.where(orders_DF['eval_set'] == 'test')] 
# orders_test = orders_DF.loc[orders_DF.eval_set=='test',('user_id', 'order_id')]
print('Prior case:', len(orders_prior))
print('Train case:', len(orders_train))
print('Test case:', len(orders_test))

# del products_order
# del train_dataframe
# del test_order
# del test_dataframe

# products_order = pd.concat([prior_order_DF, train_order_DF], axis=0)
# print(orders_DF[orders_DF['eval_set']=='test'].count())
train_dataframe = orders_train.merge(train_order_DF, how='inner', on='order_id')
prior_dataframe = orders_prior.merge(prior_order_DF, how='inner', on='order_id')
# test_dataframe  = orders_test.merge()

print(train_dataframe)
print(prior_dataframe)

test_user_id_list = orders_test['user_id']
print(len(test_user_id_list))
count = 0

# if orders_DF[orders_DF['user_id'] in test_user_id_list]:
  # count = count + 1

# print(count)

train_dataframe['reordered'] = train_dataframe['reordered'].fillna(0)
# train_dataframe = train_dataframe.set_index(['user_id','product_id'])
# train_dataframe = train_dataframe.drop(['eval_set','order_id'], axis=1)

X = train_dataframe[['user_id','product_id','order_id','add_to_cart_order','order_number','order_dow','order_hour_of_day']]
Y = train_dataframe['reordered'].astype(np.int)
print(X)
print(Y)

x_train, x_test, y_train, y_test = train_test_split(X,Y , test_size = 0.2, random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

parameters = {'eval_metric':'logloss', 
              'max_depth':'5', 
              'colsample_bytree':'0.5',    # 0.4
              'subsample':'0.75',
              'gpu_id':'0',
              'tree_method':'gpu_hist'
             }
# X_train, y_train = x_train.drop('reordered', axis=1), x_train.reordered.astype(np.int)
print(x_train.shape)
print(y_train.shape)
XGB = xgb.XGBClassifier(objective='binary:logistic', parameters=parameters, num_boost_round=10)
model = XGB.fit(x_train, y_train)
print(model)
xgb.plot_importance(model)
model.get_xgb_params()

y_pred = model.predict(x_test)
acc = accuracy_score(y_test, y_pred)
fl_score = f1_score(y_test, y_pred)

print(acc)
print(fl_score)
print(y_pred.shape)